
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl CPUBOUNDIMPL_SKEL
// ------------------------------
#ifndef CPUBOUNDIMPL_SKEL_EXPORT_H
#define CPUBOUNDIMPL_SKEL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (CPUBOUNDIMPL_SKEL_HAS_DLL)
#  define CPUBOUNDIMPL_SKEL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && CPUBOUNDIMPL_SKEL_HAS_DLL */

#if !defined (CPUBOUNDIMPL_SKEL_HAS_DLL)
#  define CPUBOUNDIMPL_SKEL_HAS_DLL 1
#endif /* ! CPUBOUNDIMPL_SKEL_HAS_DLL */

#if defined (CPUBOUNDIMPL_SKEL_HAS_DLL) && (CPUBOUNDIMPL_SKEL_HAS_DLL == 1)
#  if defined (CPUBOUNDIMPL_SKEL_BUILD_DLL)
#    define CPUBOUNDIMPL_SKEL_Export ACE_Proper_Export_Flag
#    define CPUBOUNDIMPL_SKEL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define CPUBOUNDIMPL_SKEL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* CPUBOUNDIMPL_SKEL_BUILD_DLL */
#    define CPUBOUNDIMPL_SKEL_Export ACE_Proper_Import_Flag
#    define CPUBOUNDIMPL_SKEL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define CPUBOUNDIMPL_SKEL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* CPUBOUNDIMPL_SKEL_BUILD_DLL */
#else /* CPUBOUNDIMPL_SKEL_HAS_DLL == 1 */
#  define CPUBOUNDIMPL_SKEL_Export
#  define CPUBOUNDIMPL_SKEL_SINGLETON_DECLARATION(T)
#  define CPUBOUNDIMPL_SKEL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* CPUBOUNDIMPL_SKEL_HAS_DLL == 1 */

// Set CPUBOUNDIMPL_SKEL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (CPUBOUNDIMPL_SKEL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define CPUBOUNDIMPL_SKEL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define CPUBOUNDIMPL_SKEL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !CPUBOUNDIMPL_SKEL_NTRACE */

#if (CPUBOUNDIMPL_SKEL_NTRACE == 1)
#  define CPUBOUNDIMPL_SKEL_TRACE(X)
#else /* (CPUBOUNDIMPL_SKEL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define CPUBOUNDIMPL_SKEL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (CPUBOUNDIMPL_SKEL_NTRACE == 1) */

#endif /* CPUBOUNDIMPL_SKEL_EXPORT_H */

// End of auto generated file.
