
#ifndef CPUBOUND_IDL
#define CPUBOUND_IDL

#include <Components.idl>
#include "EventTypes.idl"

module antispam
{
  component CPUBound
  {
    consumes antispam::NullEvent InPortD;
    
    consumes antispam::NullEvent InPortE;
    
    consumes antispam::NullEvent InPortC;
    
    consumes antispam::NullEvent InPortA;
    
    consumes antispam::NullEvent InPortB;
    
    publishes antispam::NullEvent OutPortB;
    
    publishes antispam::NullEvent OutPortA;
    
    publishes antispam::NullEvent OutPortD;
    
    publishes antispam::NullEvent OutPortE;
    
    publishes antispam::NullEvent OutPortC;
    
    attribute string testName;
    
    attribute string instName;
    
    attribute long logRate;
  };
  
  home CPUBoundHome
    manages CPUBound
  {
  };
};

#endif // CPUBOUND_IDL

