
#ifndef EVENTTYPES_IDL
#define EVENTTYPES_IDL

#include <Components.idl>

module antispam
{
  eventtype NullEvent
  {
    public long eventNumber;
    public long recvTime;
    public string sourceName;
  };
};

#endif // EVENTTYPES_IDL

