
#ifndef EVENTGENERATOR_IDL
#define EVENTGENERATOR_IDL

#include <Components.idl>
#include "EventTypes.idl"

module antispam
{
  component NullEventGenerator
  {
    publishes antispam::NullEvent NullEvent;
    
    attribute double publishHertz;
    
    attribute string testName;
    
    attribute string instName;
  };
  
  home NullEventGeneratorHome
    manages NullEventGenerator
  {
  };
};

#endif // EVENTGENERATOR_IDL

