#ifndef _HELLOWORLD_COMPONENTS_IDL_
#define _HELLOWORLD_COMPONENTS_IDL_

#include "HelloWorld.idl"
#include <Components.idl>

#pragma ciao lem "HelloWorld_ComponentsE.idl"

eventtype MessageEvent
{
  public string content;
  public long time;
};

component HelloReceiver
{
  consumes ::MessageEvent greeting_ospl;
  consumes ::MessageEvent greeting_ndds;
  consumes ::MessageEvent greeting_tcpip;  
};

component HelloSender
{
  emits ::MessageEvent greeting_ospl;
  emits ::MessageEvent greeting_ndds;
  emits ::MessageEvent greeting_tcpip;

  attribute string message;
};

#endif    // !defined _HELLOWORLD_COMPONENTS_IDL_

