// -*- IDL -*-

#ifndef _HELLOWORLD_IDL_
#define _HELLOWORLD_IDL_

#include <Components.idl>

struct TimeValue
{
  unsigned long sec;
  unsigned long usec;
};

eventtype Message
{
  public TimeValue time;

  public string content;
};

component HelloWorld
{
  consumes Message handle_message;

  emits Message handle_message;
};

home HelloWorldHome manages HelloWorld
{

};

#endif  // !defined _HELLOWORLD_IDL_
