
#ifndef HELLOWORLD_IDL
#define HELLOWORLD_IDL

#include <Components.idl>

struct TimeValue
{
  long sec;
  long usec;
};

eventtype Message
{
  public string content;
  public TimeValue time;
};

component HelloWorld
{
  consumes Message handle_message;

  publishes Message handle_message_ex;

  emits Message handle_message;

  readonly attribute string readonly_message;

  attribute string message;
};

home HelloWorldHome
  manages HelloWorld
{
};

#endif // HELLOWORLD_IDL

