// This file was generated by:
// $Id$

#include "PingPong_PongComponentImpl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace PingPong_PongComponentImpl
{
  //
  // PongComponent
  //
  PongComponent::PongComponent (void)
  {
    this->recvData_event_handler_.init (this, &PongComponent::push_recvData_i);
    this->register_object (&this->recvData_event_handler_);
  }

  //
  // ~PongComponent
  //
  PongComponent::~PongComponent (void)
  {
  }

  //
  // sink: recvData
  //
  void PongComponent::push_recvData (::PingPong::SimpleEvent * ev)
  {
    this->recvData_event_handler_.handle_event (ev);
  }

  //
  // sink: recvData
  //
  void PongComponent::push_recvData_i (::PingPong::SimpleEvent * ev)
  {
    this->logger_.log (LM_DEBUG, "Start processing event %d at %d", ev->eventCount (), ACE_OS::gettimeofday ().msec ());
    this->cpu_.run (30);
    this->logger_.log (LM_DEBUG, "Stopped processing event %d at %d", ev->eventCount (), ACE_OS::gettimeofday ().msec ());
    ACE_UNUSED_ARG (ev);
  }

  //
  // ccm_activate
  //
  void PongComponent::ccm_activate (void)
  {
    try
    {
      this->logger_.connect ("corbaloc:iiop:localhost:50000/LoggingClient");
      this->base_type::ccm_activate ();
    }
    catch (const CORBA::Exception & ex)
    {
      ACE_ERROR ((LM_ERROR,
                  ACE_TEXT ("%s\n"),
                  ex._info ().c_str ()));
    }
  }

  //
  // ccm_passivate
  //
  void PongComponent::ccm_passivate (void)
  {
    this->base_type::ccm_passivate ();
    //this->logger_.disconnect ();
  }
}

//
// create_PingPong_PongComponent_Impl
//
::Components::EnterpriseComponent_ptr
create_PingPong_PongComponent_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::PingPong_PongComponentImpl::PongComponent (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

