// This file was generated by:
// $Id$

#include "PingPong_PongComponentImpl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace PingPong_PongComponentImpl
{
  //
  // PongComponent
  //
  PongComponent::PongComponent (void)
  {
  }

  //
  // ~PongComponent
  //
  PongComponent::~PongComponent (void)
  {
  }

  //
  // sink: recvData
  //
  void PongComponent::push_recvData (::PingPong::SimpleEvent * ev)
  {
    ACE_UNUSED_ARG (ev);
  }
}

//
// create_PingPong_PongComponent_Impl
//
::Components::EnterpriseComponent_ptr
create_PingPong_PongComponent_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::PingPong_PongComponentImpl::PongComponent (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

