// -*- C++ -*-

//=============================================================================
/**
 *  @file         CoreDX_Publisher_Table_T.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_COREDX_PUBLISHER_TABLE_T_H_
#define _ICCM_COREDX_PUBLISHER_TABLE_T_H_

#include "cuts/iccm/arch/dds/servant/DDS_Publisher_Table_T.h"
#include "CoreDX.h"

namespace iCCM
{

/**
 * @class CoreDX_Publisher_Table_T
 */
template <typename EVENT>
class CoreDX_Publisher_Table_T :
  public DDS_Publisher_Table_T <CoreDX, EVENT>
{
public:
  /// Type definition of the base type.
  typedef DDS_Publisher_Table_T <CoreDX, EVENT> base_type;

  /// Default constructor.
  CoreDX_Publisher_Table_T (void);

  /// Destructor.
  virtual ~CoreDX_Publisher_Table_T (void);

private:
};

}

#include "CoreDX_Publisher_Table_T.cpp"

#endif  // !defined _ICCM_COREDX_PUBLISHER_TABLE_T_H_
