// -*- C++ -*-

//=============================================================================
/**
 *  @file         CoreDX_Publisher_Table.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_COREDX_PUBLISHER_TABLE_H_
#define _ICCM_COREDX_PUBLISHER_TABLE_H_

#include "CoreDX.h"
/*
#include "cuts/iccm/servant/Publisher_Table.h"

#include "CoreDX_svnt_export.h"

namespace iCCM
{
*/
/**
 * @class CoreDX_Publisher_Table
 */
/*
class ICCM_COREDX_SVNT_Export CoreDX_Publisher_Table :
  public DDS_Publisher_Table <CoreDX>
{
public:
  /// Default constructor.
  CoreDX_Publisher_Table (void);

  /// Destructor.
  virtual ~CoreDX_Publisher_Table (void);

  /// INSERT CODE HERE

private:
  /// INSERT CODE HERE
};

}

#if defined (__CUTS_INLINE__)
#include "CoreDX_Publisher_Table.inl"
#endif
*/
#endif  // !defined _ICCM_COREDX_PUBLISHER_TABLE_H_
