// -*- C++ -*-
// $Id$

//
// CUTS_TCPIP_ORB
//
CUTS_INLINE
CUTS_TCPIP_ORB::CUTS_TCPIP_ORB (void)
: listen_addr_ (CUTS_TCPIP_DEFUALT_PORT),
  acceptor_ (obj_mgr_)
{
  CUTS_TCPIP_TRACE ("CUTS_TCPIP_ORB::CUTS_TCPIP_ORB (void)");
}

//
// ~CUTS_TCPIP_ORB
//
CUTS_INLINE
CUTS_TCPIP_ORB::~CUTS_TCPIP_ORB (void)
{
  CUTS_TCPIP_TRACE ("CUTS_TCPIP_ORB::~CUTS_TCPIP_ORB (void)");
}

