// -*- C++ -*-

//=============================================================================
/**
 *  @file TCPIP_Component_Instance_Handler.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_TCPIP_COMPONENT_INSTANCE_HANDLER_H_
#define _ICCM_TCPIP_COMPONENT_INSTANCE_HANDLER_H_

#include "cuts/iccm/deployment/Component_Instance_Handler_T.h"
#include "TCPIP_Container.h"
#include "cuts/iccm/arch/tcpip/stub/TCPIP_ORB.h"
#include "cuts/iccm/arch/tcpip/stub/TCPIP_ORB_Task.h"

#include "TCPIP_Deployment_Handlers_export.h"

namespace iCCM
{

/**
 * @class TCPIP_Component_Instance_Handler
 *
 * TCPIP implementation of the deployment handlers for component
 * instances.
 */
class  ICCM_TCPIP_DEPLOYMENT_HANDLERS_Export TCPIP_Component_Instance_Handler :
  public Component_Instance_Handler_T <TCPIP_Component_Instance_Handler,
                                      ::DAnCE::InstanceDeploymentHandler,
                                      TCPIP_Container>
{
public:
  /// Type definition of the base type.
  typedef Component_Instance_Handler_T <TCPIP_Component_Instance_Handler,
                                       ::DAnCE::InstanceDeploymentHandler,
                                       TCPIP_Container> base_type;

  /// Default constructor.
  TCPIP_Component_Instance_Handler (void);

  /// Destructor.
  virtual ~TCPIP_Component_Instance_Handler (void);

  /**
   * Configure the instance handler. The deployment properties passed
   * into this function are the ones attached to the Node in the
   * deployment model.
   *
   * @param[in]           config          Configuration properties
   */
  virtual void configure (const Deployment::Properties & config);

  /// Close the instance handler.
  virtual void close (void);

  /// TCPIP ORB getter
  TCPIP_ORB & the_ORB (void);

private:
  /// The ORB for the component server.
  TCPIP_ORB tcpip_orb_;

  /// The active object for this handler.
  CUTS_TCPIP_ORB_Task orb_task_;
};

}

extern "C"
ICCM_TCPIP_DEPLOYMENT_HANDLERS_Export
::DAnCE::InstanceDeploymentHandler_ptr
create_iCCM_TCPIP_Component_Instance_Handler (void);

#if defined (__CUTS_INLINE__)
#include "TCPIP_Component_Instance_Handler.inl"
#endif

#endif  // !defined _ICCM_TCPIP_COMPONENT_INSTANCE_HANDLER_H_
