// -*- C++ -*-

//=============================================================================
/**
 *  @file         TCPIP_Container.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_TCPIP_CONTAINER_H_
#define _ICCM_TCPIP_CONTAINER_H_

#include "cuts/iccm/deployment/Container_T.h"

#include "cuts/iccm/arch/tcpip/servant/TCPIP_Servant.h"
#include "TCPIP_Container_Strategy.h"

namespace iCCM
{

// Forward decl.
class TCPIP_Component_Instance_Handler;

/**
 * @class TCPIP_Container
 *
 * iCCM container implementation for the TCPIP architecture.
 */
class ICCM_TCPIP_DEPLOYMENT_HANDLERS_Export TCPIP_Container :
  public Container_T <TCPIP_Container,
                      TCPIP_Component_Instance_Handler,
                      TCPIP_Container_Strategy,
                      TCPIP_Servant>
{
public:
  /// Type definition of the base type.
  typedef
    Container_T <TCPIP_Container,
                 TCPIP_Component_Instance_Handler,
                 TCPIP_Container_Strategy,
                 TCPIP_Servant> base_type;

  /**
   * Initializing constructor.
   *
   * @param[in]           handler           Pointer to instance handler
   * @param[in]           poa               PortableServer for container
   */
  TCPIP_Container (
    TCPIP_Component_Instance_Handler * handler,
     ::PortableServer::POA_ptr the_POA);

  /// Destructor.
  virtual ~TCPIP_Container (void);
};

}

#if defined (__CUTS_INLINE__)
#include "TCPIP_Container.inl"
#endif

#endif  // !defined _ICCM_TCPIP_CONTAINER_H_
