// -*- IDL -*-

#ifndef _CUTS_TESTING_IDL_
#define _CUTS_TESTING_IDL_

#include "cuts/idl/UUID.idl"

module CUTS
{
  /**
   * @struct TestDetails
   */
  struct TestDetails
  {
    /// The UUID assigned to the test.
    UUID uid;

    /// The name of the test.
    string name;
  };

  /**
   * @interface TestManager
   */
  interface TestManager
  {
    /// Retrieve information about the current test.
    readonly attribute TestDetails details;

    /// Shutdown the current test.
    oneway void shutdown ();
  };
};

#endif  // !defined _CUTS_TESTING_IDL_
