// This file was generated by:
// $Id$

#include "HelloReceiverImpl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace HelloReceiverImpl
{
  //
  // HelloReceiver
  //
  HelloReceiver::HelloReceiver (void)
  {
  }

  //
  // ~HelloReceiver
  //
  HelloReceiver::~HelloReceiver (void)
  {
  }

  //
  // sink: greeting
  //
  void HelloReceiver::push_greeting (::MessageEvent * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
                ACE_TEXT ("content = %s\n"),
                ev->content ()));

    ACE_UNUSED_ARG (ev);
  }
}

//
// create_HelloReceiver_Impl
//
::Components::EnterpriseComponent_ptr
create_HelloReceiver_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::HelloReceiverImpl::HelloReceiver (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

