#ifndef _COMPONENTTYPES_IDL_
#define _COMPONENTTYPES_IDL_

#include <Components.idl>
#include "./EventTypes.idl"

#pragma ciao lem "ComponentTypesE.idl"

module SLICE
{
  
  component Effector
  {
    consumes ::SLICE::SimpleEvent effectorSettings;
    
  };
  
  component ConfigOp
  {
    consumes ::SLICE::SimpleEvent recvEvent;
    publishes ::SLICE::SimpleEvent sendEvent;
    
  };
  
  component Sensor
  {
    publishes ::SLICE::SimpleEvent sensorData;
    
  };
  
  component PlannerOne
  {
    consumes ::SLICE::SimpleEvent recvEvent;
    publishes ::SLICE::SimpleEvent pushEvent;
    
  };
  
  component PlannerTwo
  {
    consumes ::SLICE::SimpleEvent recvEvent;
    publishes ::SLICE::SimpleEvent pushEvent;
    
  };
  
};

#endif    // !defined _COMPONENTTYPES_IDL_

