#ifndef _EVENTTYPES_IDL_
#define _EVENTTYPES_IDL_

#include <Components.idl>

#pragma ciao lem "EventTypesE.idl"

module SLICE
{
  eventtype SimpleEvent
  {
    public unsigned long eventCount;
    
  };
  
};

#endif    // !defined _EVENTTYPES_IDL_

