// This file was generated by:
// $Id$

#include "SLICE_PlannerOneImpl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace SLICE_PlannerOneImpl
{
  //
  // PlannerOne
  //
  PlannerOne::PlannerOne (void)
  {
  }

  //
  // ~PlannerOne
  //
  PlannerOne::~PlannerOne (void)
  {
  }

  //
  // sink: recvEvent
  //
  void PlannerOne::push_recvEvent (::SLICE::SimpleEvent * ev)
  {
    ACE_UNUSED_ARG (ev);
  }
}

//
// create_SLICE_PlannerOne_Impl
//
::Components::EnterpriseComponent_ptr
create_SLICE_PlannerOne_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::SLICE_PlannerOneImpl::PlannerOne (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

