// This file was generated by:
// $Id$

#include "SLICE_ConfigOpImpl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace SLICE_ConfigOpImpl
{
  //
  // ConfigOp
  //
  ConfigOp::ConfigOp (void)
  {
  }

  //
  // ~ConfigOp
  //
  ConfigOp::~ConfigOp (void)
  {
  }

  //
  // sink: recvEvent
  //
  void ConfigOp::push_recvEvent (::SLICE::SimpleEvent * ev)
  {
    this->cpuGen_.run (30);
    CUTS_CCM_Event_T <OBV_SLICE::SimpleEvent> __event_100000091__;
    __event_100000091__->content ().eventCount = ev->content ().eventCount;
    this->ctx_->push_sendEvent (__event_100000091__.in ());

    ACE_UNUSED_ARG (ev);
  }
}

//
// create_SLICE_ConfigOp_Impl
//
::Components::EnterpriseComponent_ptr
create_SLICE_ConfigOp_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::SLICE_ConfigOpImpl::ConfigOp (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

