// This file was generated by:
// $Id$

#include "SLICE_SensorImpl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace SLICE_SensorImpl
{
  //
  // Sensor
  //
  Sensor::Sensor (void)
  : eventCount_ (0)
  {
    this->periodic_periodicData_.init (this, &Sensor::periodic_periodicData);
    this->periodic_periodicData_.configure (CUTS_Periodic_Event::PE_CONSTANT, 10);
    this->register_object (&this->periodic_periodicData_);
  }

  //
  // ~Sensor
  //
  Sensor::~Sensor (void)
  {
  }

  //
  // PeriodicEvent: periodicData
  //
  void Sensor::periodic_periodicData (void)
  {
    this->logger_.log (LM_INFO, "sent event %d at %u", this->eventCount_, ACE_OS::gettimeofday ().get_msec ());
    CUTS_CCM_Event_T <OBV_SLICE::SimpleEvent> __event_100000016__;
    __event_100000016__->content ().eventCount = this->eventCount_;
    this->ctx_->push_sensorData (__event_100000016__.in ());

    ++ this->eventCount_;
  }

  //
  // ccm_activate
  //
  void Sensor::ccm_activate (void)
  {
    this->logger_.connect ("corbaloc:iiop:localhost:50000/LoggingClient");
    this->base_type::ccm_activate ();
  }

  //
  // ccm_passivate
  //
  void Sensor::ccm_passivate (void)
  {
    this->base_type::ccm_passivate ();
    this->logger_.disconnect ();
  }
}

//
// create_SLICE_Sensor_Impl
//
::Components::EnterpriseComponent_ptr
create_SLICE_Sensor_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::SLICE_SensorImpl::Sensor (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

