
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl ISISLAB_EMULATION_GENERATOR
// ------------------------------
#ifndef ISISLAB_EMULATION_GENERATOR_EXPORT_H
#define ISISLAB_EMULATION_GENERATOR_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (ISISLAB_EMULATION_GENERATOR_HAS_DLL)
#  define ISISLAB_EMULATION_GENERATOR_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && ISISLAB_EMULATION_GENERATOR_HAS_DLL */

#if !defined (ISISLAB_EMULATION_GENERATOR_HAS_DLL)
#  define ISISLAB_EMULATION_GENERATOR_HAS_DLL 1
#endif /* ! ISISLAB_EMULATION_GENERATOR_HAS_DLL */

#if defined (ISISLAB_EMULATION_GENERATOR_HAS_DLL) && (ISISLAB_EMULATION_GENERATOR_HAS_DLL == 1)
#  if defined (ISISLAB_EMULATION_GENERATOR_BUILD_DLL)
#    define ISISLAB_EMULATION_GENERATOR_Export ACE_Proper_Export_Flag
#    define ISISLAB_EMULATION_GENERATOR_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define ISISLAB_EMULATION_GENERATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* ISISLAB_EMULATION_GENERATOR_BUILD_DLL */
#    define ISISLAB_EMULATION_GENERATOR_Export ACE_Proper_Import_Flag
#    define ISISLAB_EMULATION_GENERATOR_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define ISISLAB_EMULATION_GENERATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* ISISLAB_EMULATION_GENERATOR_BUILD_DLL */
#else /* ISISLAB_EMULATION_GENERATOR_HAS_DLL == 1 */
#  define ISISLAB_EMULATION_GENERATOR_Export
#  define ISISLAB_EMULATION_GENERATOR_SINGLETON_DECLARATION(T)
#  define ISISLAB_EMULATION_GENERATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* ISISLAB_EMULATION_GENERATOR_HAS_DLL == 1 */

// Set ISISLAB_EMULATION_GENERATOR_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (ISISLAB_EMULATION_GENERATOR_NTRACE)
#  if (ACE_NTRACE == 1)
#    define ISISLAB_EMULATION_GENERATOR_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define ISISLAB_EMULATION_GENERATOR_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !ISISLAB_EMULATION_GENERATOR_NTRACE */

#if (ISISLAB_EMULATION_GENERATOR_NTRACE == 1)
#  define ISISLAB_EMULATION_GENERATOR_TRACE(X)
#else /* (ISISLAB_EMULATION_GENERATOR_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define ISISLAB_EMULATION_GENERATOR_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (ISISLAB_EMULATION_GENERATOR_NTRACE == 1) */

#endif /* ISISLAB_EMULATION_GENERATOR_EXPORT_H */

// End of auto generated file.
