// -*- IDL -*-

//=============================================================================
/**
 * @file      Quotas_Integrator.idl
 *
 * $Id$
 *
 * @author    James H. Hill
 */
//=============================================================================

#ifndef _QUOTAS_INTEGRATOR_IDL_
#define _QUOTAS_INTEGRATOR_IDL_

#include <Gme.idl>

[
	uuid(35925D3C-8827-4978-9D44-E6E1701C4C46),
	version(1.0),
]
library Quotas_Integrator
{
	importlib("stdole32.tlb");

	[uuid(06E81B58-9B3E-4814-AA48-411A7038E821)]
	coclass Quotas_Integrator_Interpreter
	{
		[default] interface IMgaComponentEx;
		interface IMgaComponent;
		interface IMgaVersionInfo;
	};
};

#endif

