// This file was generated by:
// $Id$

#include "Tput_Receiver_Component.h"
#include "ace/streams.h"

namespace ReceiverComponentImpl
{
  //
  // ReceiverComponent
  //
  ReceiverComponent::ReceiverComponent (void)
  {
  }

  //
  // ~ReceiverComponent
  //
  ReceiverComponent::~ReceiverComponent (void)
  {
  }

  //
  // ccm_activate
  //
  void ReceiverComponent::ccm_activate (void)
  {
    // Reset the event count.
    this->count_ = 0;
    this->timer_.start ();
  }

  //
  // ccm_passivate
  //
  void ReceiverComponent::ccm_passivate (void)
  {
    // Stop the timer.
    this->timer_.stop ();

    // Calculate the events/second.
    ACE_hrtime_t elapsed;
    this->timer_.elapsed_time (elapsed);

    double tput = ((double)this->count_ / (double)elapsed) * (double)ACE_ONE_SECOND_IN_NSECS;

    ACE_ERROR ((LM_ERROR,
                ACE_TEXT ("# events recv: %d\n")
                ACE_TEXT ("receiver throughput: %f\n"),
                this->count_,
                tput));
  }

  //
  // push_size8data
  //
  void ReceiverComponent::push_size8data (Size8DataEvent * )
  {
    ++ this->count_;
  }

  //
  // push_size16data
  //
  void ReceiverComponent::push_size16data (Size16DataEvent * )
  {

  }

  //
  // push_size32data
  //
  void ReceiverComponent::push_size32data (Size32DataEvent * )
  {

  }

  //
  // push_size64data
  //
  void ReceiverComponent::push_size64data (Size64DataEvent * )
  {

  }
}

//
// create_ReceiverComponent_Impl
//
::Components::EnterpriseComponent_ptr
create_TPUT_Receiver_Component_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::ReceiverComponentImpl::ReceiverComponent (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

