// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// e:\proj\vc11\middleware\tao\tao_idl\be\be_codegen.cpp:1254

#ifndef CIAO_SERVANT_HELLOWORLD_SVNT_T_FDIOZP_CPP_
#define CIAO_SERVANT_HELLOWORLD_SVNT_T_FDIOZP_CPP_


#include "ciao/Valuetype_Factories/Cookies.h"
#include "tao/SystemException.h"
#include "tao/Valuetype/ValueFactory.h"
#include "tao/ORB_Core.h"
#include "ace/SString.h"

#endif /* ifndef */

