// -*- IDL -*-

#ifndef _PINGPONG_OSPL_IDL_
#define _PINGPONG_OSPL_IDL_

#include "PingPong.idl"
#include <Components.idl>

module PingPong
{
  eventtype PP_min_msg_ev
  {
    public ::PingPong::PP_min_msg content;
  };

  eventtype PP_fixed_msg_ev
  {
    public ::PingPong::PP_fixed_msg content;
  };

  eventtype PP_seq_msg_ev
  {
    public ::PingPong::PP_seq_msg content;
  };

  eventtype PP_string_msg_ev
  {
     public ::PingPong::PP_string_msg content;
  };

  eventtype PP_array_msg_ev
  {
    public ::PingPong::PP_array_msg content;
  };

  eventtype PP_bseq_msg_ev
  {
    public ::PingPong::PP_bseq_msg content;
  };

  eventtype PP_quit_msg_ev
  {
    public ::PingPong::PP_quit_msg content;
  };
};

#endif  // _PINGPONG_OSPL_IDL_

