// -*- C++ -*-

//==============================================================================
/**
 *  @file       Tron_Servant.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//==============================================================================

#ifndef _ICCM_TRON_SERVANT_H_
#define _ICCM_TRON_SERVANT_H_

#include "cuts/iccm/servant/Servant.h"

#include "Tron_EventConsumer.h"
#include "Tron_Publisher.h"
#include "Tron_Publisher_Table.h"
#include "tron/adapter.h"
#include "../deployment/Tron_Consumer_Map_Type.h"

namespace iCCM
{

/**
 * @class Tron_Servant
 *
 * Base class for all Tron servant objects. This class enables
 * the container to send commands to the servant, such as
 * domain-specific configuration information.
 */
class ICCM_TRON_SVNT_Export Tron_Servant :
  public Servant
{
public:
  /// Trait definitions for iCCM::Servant_T object.
  typedef Tron_EventConsumer eventconsumer_type;
  typedef Tron_Publisher publisher_type;
  typedef Tron_Publisher_Table publisher_table_type;

  /// Default constructor.
  Tron_Servant (const char * name);

  /// Destructor.
  virtual ~Tron_Servant (void);

  /// Initalize the servant for tron
  virtual void init (Reporter * reporter, tron_consumer_map_type & consumer_map) = 0;
};

}

#if defined (__CUTS_INLINE__)
#include "Tron_Servant.inl"
#endif

#endif  // !defined _ICCM_Tron_SERVANT_H_
