// -*- C++ -*-

//=============================================================================
/**
 *  @file         TCPIP_Publisher_Table_T.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_TCPIP_PUBLISHER_TABLE_T_H_
#define _ICCM_TCPIP_PUBLISHER_TABLE_T_H_

#include "cuts/iccm/servant/Publisher_Table_T.h"

#include "TCPIP_Publisher_Table.h"
#include "TCPIP_Publisher_T.h"

namespace iCCM
{

/**
 * @class TCPIP_Publisher_Table_T
 */
template <typename EVENT>
class TCPIP_Publisher_Table_T :
  public Publisher_Table_T < TCPIP_Publisher_Table, TCPIP_Publisher_T <EVENT>, true >
{
public:
  /// Type definition of the base type.
  typedef Publisher_Table_T < TCPIP_Publisher_Table,
                              TCPIP_Publisher_T <EVENT>,
                              true > base_type;

  /// Default constructor.
  TCPIP_Publisher_Table_T (void);

  /// Destructor.
  virtual ~TCPIP_Publisher_Table_T (void);

  /**
   * Subscribe an event consumer.
   *
   * @param[in]       consumer          Event consumer object
   * @return          Cookie object
   */
  virtual ::Components::Cookie * subscribe (::Components::EventConsumerBase_ptr);

  /**
   * Unsubscribe an event consumer.
   *
   * @param[in]       consumer         Cookie object
   * @return          Event consumer object
   */
  virtual ::Components::EventConsumerBase_ptr unsubscribe (::Components::Cookie *);

  /// Send an event.
  void send_event (EVENT * ev);

  /// Allocate a new event.
  EVENT * allocate_event (void);

private:
  typedef typename Publisher_Table_T < TCPIP_Publisher_Table,
                                       TCPIP_Publisher_T <EVENT>,
                                       true >::consumer_table_t consumer_table_t;
};

}

#include "TCPIP_Publisher_Table_T.cpp"

#endif  // !defined _ICCM_TCPIP_PUBLISHER_TABLE_T_H_
