// This file was generated by:
// $Id$

#include "SimpleComponent_Basic_Impl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace SimpleComponent_Basic_Impl
{
  //
  // SimpleComponent
  //
  SimpleComponent::SimpleComponent (void)
  : isActive_ (true),
    eventCount_ (0)
  {
    this->periodic_sendData_.init (this, &SimpleComponent::periodic_sendData);
    this->periodic_sendData_.configure (CUTS_Periodic_Event::PE_CONSTANT, 10);
    this->register_object (&this->periodic_sendData_);
  }

  //
  // ~SimpleComponent
  //
  SimpleComponent::~SimpleComponent (void)
  {
  }

  //
  // sink: ospl_read_test_data
  //
  void SimpleComponent::push_ospl_read_test_data (::Outer::TestData_DDS * ev)
  {
    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000044__;
    this->ctx_->push_app_op_ndds (__event_100000044__.in ());

    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: corba_read_test_data
  //
  void SimpleComponent::push_corba_read_test_data (::Outer::TestData_DDS * ev)
  {
    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000009__;
    this->ctx_->push_app_op_ospl (__event_100000009__.in ());

    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: ndds_read_test_data
  //
  void SimpleComponent::push_ndds_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: tcpip_read_test_data
  //
  void SimpleComponent::push_tcpip_read_test_data (::Outer::TestData_DDS * ev)
  {
    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000006__;
    this->ctx_->push_app_op_corba (__event_100000006__.in ());

    ACE_UNUSED_ARG (ev);
  }

  //
  // PeriodicEvent: sendData
  //
  void SimpleComponent::periodic_sendData (void)
  {
    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000007__;
    this->ctx_->push_app_op_tcpip (__event_100000007__.in ());
  }
}

//
// create_SimpleComponent_Basic_Impl
//
::Components::EnterpriseComponent_ptr 
create_SimpleComponent_Basic_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval, 
                  ::SimpleComponent_Basic_Impl::SimpleComponent (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

