// This file was generated by:
// $Id$

#include "SimpleComponent_Impl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace SimpleComponent_Basic_Impl
{
  //
  // SimpleComponent
  //
  SimpleComponent::SimpleComponent (void)
  : eventCount_ (0),
    isActive_ (true)
  {
    this->periodic_sendData_.init (this, &SimpleComponent::periodic_sendData);
    this->periodic_sendData_.configure (CUTS_Periodic_Event::PE_CONSTANT, 10);
    this->register_object (&this->periodic_sendData_);
  }

  //
  // ~SimpleComponent
  //
  SimpleComponent::~SimpleComponent (void)
  {
  }

  //
  // sink: tcpip_read_test_data
  //
  void SimpleComponent::push_tcpip_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
                "%T (%t) - %M - received a TCP/IP event\n"));

    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: corba_read_test_data
  //
  void SimpleComponent::push_corba_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
                "%T (%t) - %M - received a CORBA event\n"));

    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: dds_read_test_data
  //
  void SimpleComponent::push_dds_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
                "%T (%t) - %M - received a DDS event\n"));

    ACE_UNUSED_ARG (ev);
  }

  //
  // PeriodicEvent: sendData
  //
  void SimpleComponent::periodic_sendData (void)
  {
    ACE_DEBUG ((LM_DEBUG,
                "%T (%t) - %M - sending event %d\n",
                ++ this->eventCount_));

    CUTS_CCM_Event_T < ::OBV_Outer::TestData_DDS > event;

    this->ctx_->push_app_op_tcpip (event.in ());
    this->ctx_->push_app_op_corba (event.in ());
    this->ctx_->push_app_op_dds (event.in ());
  }

  //
  // ccm_activate
  //
  void SimpleComponent::ccm_activate (void)
  {
    this->base_type::ccm_activate ();
  }
}

//
// create_SimpleComponent_Basic_Impl
//
::Components::EnterpriseComponent_ptr
create_SimpleComponent_Basic_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval,
                  ::SimpleComponent_Basic_Impl::SimpleComponent (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

