
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SIMPLECOMPONENT_BASIC_IMPL
// ------------------------------
#ifndef SIMPLECOMPONENT_BASIC_IMPL_EXPORT_H
#define SIMPLECOMPONENT_BASIC_IMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL)
#  define SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL */

#if !defined (SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL)
#  define SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL 1
#endif /* ! SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL */

#if defined (SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL) && (SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL == 1)
#  if defined (SIMPLECOMPONENT_BASIC_IMPL_BUILD_DLL)
#    define SIMPLECOMPONENT_BASIC_IMPL_Export ACE_Proper_Export_Flag
#    define SIMPLECOMPONENT_BASIC_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SIMPLECOMPONENT_BASIC_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SIMPLECOMPONENT_BASIC_IMPL_BUILD_DLL */
#    define SIMPLECOMPONENT_BASIC_IMPL_Export ACE_Proper_Import_Flag
#    define SIMPLECOMPONENT_BASIC_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SIMPLECOMPONENT_BASIC_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SIMPLECOMPONENT_BASIC_IMPL_BUILD_DLL */
#else /* SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL == 1 */
#  define SIMPLECOMPONENT_BASIC_IMPL_Export
#  define SIMPLECOMPONENT_BASIC_IMPL_SINGLETON_DECLARATION(T)
#  define SIMPLECOMPONENT_BASIC_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SIMPLECOMPONENT_BASIC_IMPL_HAS_DLL == 1 */

// Set SIMPLECOMPONENT_BASIC_IMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SIMPLECOMPONENT_BASIC_IMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SIMPLECOMPONENT_BASIC_IMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SIMPLECOMPONENT_BASIC_IMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SIMPLECOMPONENT_BASIC_IMPL_NTRACE */

#if (SIMPLECOMPONENT_BASIC_IMPL_NTRACE == 1)
#  define SIMPLECOMPONENT_BASIC_IMPL_TRACE(X)
#else /* (SIMPLECOMPONENT_BASIC_IMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SIMPLECOMPONENT_BASIC_IMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SIMPLECOMPONENT_BASIC_IMPL_NTRACE == 1) */

#endif /* SIMPLECOMPONENT_BASIC_IMPL_EXPORT_H */

// End of auto generated file.
