// This file was generated by:
// $Id$

#include "SimpleComponent_Basic_Impl.h"
#include "cuts/arch/ccm/CCM_Events_T.h"

namespace SimpleComponent_Basic_Impl
{
  //
  // SimpleComponent
  //
  SimpleComponent::SimpleComponent (void)
  : eventCount_ (0),
    isActive_ (true)
  {
    this->periodic_sendData_.init (this, &SimpleComponent::periodic_sendData);
    this->periodic_sendData_.configure (CUTS_Periodic_Event::PE_CONSTANT, 10);
    this->register_object (&this->periodic_sendData_);
  }

  //
  // ~SimpleComponent
  //
  SimpleComponent::~SimpleComponent (void)
  {
  }

  //
  // sink: dds_read_test_data
  //
  void SimpleComponent::push_dds_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
		"%T (%t) - %M - received a OpenSpliceDDS event\n"));

    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: corba_read_test_data
  //
  void SimpleComponent::push_corba_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
		"%T (%t) - %M - received a CORBA event\n"));

    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000042__;
    this->ctx_->push_app_op_dds (__event_100000042__.in ());

    ACE_UNUSED_ARG (ev);
  }

  //
  // sink: tcpip_read_test_data
  //
  void SimpleComponent::push_tcpip_read_test_data (::Outer::TestData_DDS * ev)
  {
    ACE_DEBUG ((LM_DEBUG,
		"%T (%t) - %M - received a TCP/IP event\n"));

    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000007__;
    this->ctx_->push_app_op_corba (__event_100000007__.in ());

    ACE_UNUSED_ARG (ev);
  }

  //
  // PeriodicEvent: sendData
  //
  void SimpleComponent::periodic_sendData (void)
  {
    ACE_DEBUG ((LM_DEBUG,
		"%T (%t) - %M - sending a TCP/IP event\n"));

    CUTS_CCM_Event_T <OBV_Outer::TestData_DDS> __event_100000008__;
    this->ctx_->push_app_op_tcpip (__event_100000008__.in ());
  }
}

//
// create_SimpleComponent_Basic_Impl
//
::Components::EnterpriseComponent_ptr 
create_SimpleComponent_Basic_Impl (void)
{
  ::Components::EnterpriseComponent_ptr retval =
    ::Components::EnterpriseComponent::_nil ();

  ACE_NEW_RETURN (retval, 
                  ::SimpleComponent_Basic_Impl::SimpleComponent (),
                  ::Components::EnterpriseComponent::_nil ());

  return retval;
}


// end of auto-generated file

