// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.8
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL___OPENSPLICE_HELLOWORLDDCPSC_ZZGY0M_H_
#define _TAO_IDL___OPENSPLICE_HELLOWORLDDCPSC_ZZGY0M_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "../HelloWorld_stub_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "dds_dcpsC.h"
#include "HelloWorldC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 8
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO HELLOWORLD_STUB_Export

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

#if !defined (_MESSAGESEQ_CH_)
#define _MESSAGESEQ_CH_

class MessageSeq;

typedef
  ::TAO_VarSeq_Var_T<
      MessageSeq
    >
  MessageSeq_var;

typedef
  ::TAO_Seq_Out_T<
      MessageSeq
    >
  MessageSeq_out;

class HELLOWORLD_STUB_Export MessageSeq
  : public
      ::TAO::unbounded_value_sequence<
          Message
        >
{
public:
  MessageSeq (void);
  MessageSeq ( ::CORBA::ULong max);
  MessageSeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    Message* buffer,
    ::CORBA::Boolean release = false);
  MessageSeq (const MessageSeq &);
  virtual ~MessageSeq (void);
  

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_type.cpp:307

  
  typedef MessageSeq_var _var_type;
  typedef MessageSeq_out _out_type;
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_interface.cpp:750

#if !defined (_MESSAGETYPESUPPORTINTERFACE__VAR_OUT_CH_)
#define _MESSAGETYPESUPPORTINTERFACE__VAR_OUT_CH_

class MessageTypeSupportInterface;
typedef MessageTypeSupportInterface *MessageTypeSupportInterface_ptr;

typedef
  TAO_Objref_Var_T<
      MessageTypeSupportInterface
    >
  MessageTypeSupportInterface_var;

typedef
  TAO_Objref_Out_T<
      MessageTypeSupportInterface
    >
  MessageTypeSupportInterface_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

class HELLOWORLD_STUB_Export MessageTypeSupportInterface
  : public virtual ::DDS::TypeSupport

{
public:

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_type.cpp:307

  typedef MessageTypeSupportInterface_ptr _ptr_type;
  typedef MessageTypeSupportInterface_var _var_type;
  typedef MessageTypeSupportInterface_out _out_type;

  // The static operations.
  static MessageTypeSupportInterface_ptr _duplicate (MessageTypeSupportInterface_ptr obj);

  static void _tao_release (MessageTypeSupportInterface_ptr obj);

  static MessageTypeSupportInterface_ptr _narrow (::CORBA::Object_ptr obj);
  static MessageTypeSupportInterface_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
  static MessageTypeSupportInterface_ptr _nil (void);

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

  virtual ::CORBA::Boolean _is_a (const char *type_id);
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);

protected:
  // Abstract or local interface only.
  MessageTypeSupportInterface (void);

  

  virtual ~MessageTypeSupportInterface (void);

private:
  // Private and unimplemented for concrete interfaces.
  MessageTypeSupportInterface (const MessageTypeSupportInterface &);

  void operator= (const MessageTypeSupportInterface &);
};

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_interface.cpp:750

#if !defined (_MESSAGEDATAWRITER__VAR_OUT_CH_)
#define _MESSAGEDATAWRITER__VAR_OUT_CH_

class MessageDataWriter;
typedef MessageDataWriter *MessageDataWriter_ptr;

typedef
  TAO_Objref_Var_T<
      MessageDataWriter
    >
  MessageDataWriter_var;

typedef
  TAO_Objref_Out_T<
      MessageDataWriter
    >
  MessageDataWriter_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

class HELLOWORLD_STUB_Export MessageDataWriter
  : public virtual ::DDS::DataWriter

{
public:

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_type.cpp:307

  typedef MessageDataWriter_ptr _ptr_type;
  typedef MessageDataWriter_var _var_type;
  typedef MessageDataWriter_out _out_type;

  // The static operations.
  static MessageDataWriter_ptr _duplicate (MessageDataWriter_ptr obj);

  static void _tao_release (MessageDataWriter_ptr obj);

  static MessageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
  static MessageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
  static MessageDataWriter_ptr _nil (void);

  virtual ::DDS::InstanceHandle_t register_instance (
    const ::Message & instance_data) = 0;

  virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
    const ::Message & instance_data,
    const ::DDS::Time_t & source_timestamp) = 0;

  virtual ::DDS::ReturnCode_t unregister_instance (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle,
    const ::DDS::Time_t & source_timestamp) = 0;

  virtual ::DDS::ReturnCode_t write (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::ReturnCode_t write_w_timestamp (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle,
    const ::DDS::Time_t & source_timestamp) = 0;

  virtual ::DDS::ReturnCode_t dispose (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::ReturnCode_t dispose_w_timestamp (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle,
    const ::DDS::Time_t & source_timestamp) = 0;

  virtual ::DDS::ReturnCode_t writedispose (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::ReturnCode_t writedispose_w_timestamp (
    const ::Message & instance_data,
    ::DDS::InstanceHandle_t handle,
    const ::DDS::Time_t & source_timestamp) = 0;

  virtual ::DDS::ReturnCode_t get_key_value (
    ::Message & key_holder,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::InstanceHandle_t lookup_instance (
    const ::Message & instance_data) = 0;

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

  virtual ::CORBA::Boolean _is_a (const char *type_id);
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);

protected:
  // Abstract or local interface only.
  MessageDataWriter (void);

  

  virtual ~MessageDataWriter (void);

private:
  // Private and unimplemented for concrete interfaces.
  MessageDataWriter (const MessageDataWriter &);

  void operator= (const MessageDataWriter &);
};

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_interface.cpp:750

#if !defined (_MESSAGEDATAREADER__VAR_OUT_CH_)
#define _MESSAGEDATAREADER__VAR_OUT_CH_

class MessageDataReader;
typedef MessageDataReader *MessageDataReader_ptr;

typedef
  TAO_Objref_Var_T<
      MessageDataReader
    >
  MessageDataReader_var;

typedef
  TAO_Objref_Out_T<
      MessageDataReader
    >
  MessageDataReader_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

class HELLOWORLD_STUB_Export MessageDataReader
  : public virtual ::DDS::DataReader

{
public:

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_type.cpp:307

  typedef MessageDataReader_ptr _ptr_type;
  typedef MessageDataReader_var _var_type;
  typedef MessageDataReader_out _out_type;

  // The static operations.
  static MessageDataReader_ptr _duplicate (MessageDataReader_ptr obj);

  static void _tao_release (MessageDataReader_ptr obj);

  static MessageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
  static MessageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
  static MessageDataReader_ptr _nil (void);

  virtual ::DDS::ReturnCode_t read (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t take (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t read_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t take_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t read_next_sample (
    ::Message & received_data,
    ::DDS::SampleInfo & sample_info) = 0;

  virtual ::DDS::ReturnCode_t take_next_sample (
    ::Message & received_data,
    ::DDS::SampleInfo & sample_info) = 0;

  virtual ::DDS::ReturnCode_t read_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t take_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t read_next_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t take_next_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t return_loan (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq) = 0;

  virtual ::DDS::ReturnCode_t get_key_value (
    ::Message & key_holder,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::InstanceHandle_t lookup_instance (
    const ::Message & instance) = 0;

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

  virtual ::CORBA::Boolean _is_a (const char *type_id);
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);

protected:
  // Abstract or local interface only.
  MessageDataReader (void);

  

  virtual ~MessageDataReader (void);

private:
  // Private and unimplemented for concrete interfaces.
  MessageDataReader (const MessageDataReader &);

  void operator= (const MessageDataReader &);
};

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_interface.cpp:750

#if !defined (_MESSAGEDATAREADERVIEW__VAR_OUT_CH_)
#define _MESSAGEDATAREADERVIEW__VAR_OUT_CH_

class MessageDataReaderView;
typedef MessageDataReaderView *MessageDataReaderView_ptr;

typedef
  TAO_Objref_Var_T<
      MessageDataReaderView
    >
  MessageDataReaderView_var;

typedef
  TAO_Objref_Out_T<
      MessageDataReaderView
    >
  MessageDataReaderView_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

class HELLOWORLD_STUB_Export MessageDataReaderView
  : public virtual ::DDS::DataReaderView

{
public:

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_type.cpp:307

  typedef MessageDataReaderView_ptr _ptr_type;
  typedef MessageDataReaderView_var _var_type;
  typedef MessageDataReaderView_out _out_type;

  // The static operations.
  static MessageDataReaderView_ptr _duplicate (MessageDataReaderView_ptr obj);

  static void _tao_release (MessageDataReaderView_ptr obj);

  static MessageDataReaderView_ptr _narrow (::CORBA::Object_ptr obj);
  static MessageDataReaderView_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
  static MessageDataReaderView_ptr _nil (void);

  virtual ::DDS::ReturnCode_t read (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t take (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t read_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t take_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t read_next_sample (
    ::Message & received_data,
    ::DDS::SampleInfo & sample_info) = 0;

  virtual ::DDS::ReturnCode_t take_next_sample (
    ::Message & received_data,
    ::DDS::SampleInfo & sample_info) = 0;

  virtual ::DDS::ReturnCode_t read_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t take_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t read_next_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t take_next_instance (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::SampleStateMask sample_states,
    ::DDS::ViewStateMask view_states,
    ::DDS::InstanceStateMask instance_states) = 0;

  virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq,
    ::CORBA::Long max_samples,
    ::DDS::InstanceHandle_t a_handle,
    ::DDS::ReadCondition_ptr a_condition) = 0;

  virtual ::DDS::ReturnCode_t return_loan (
    ::MessageSeq & received_data,
    ::DDS::SampleInfoSeq & info_seq) = 0;

  virtual ::DDS::ReturnCode_t get_key_value (
    ::Message & key_holder,
    ::DDS::InstanceHandle_t handle) = 0;

  virtual ::DDS::InstanceHandle_t lookup_instance (
    const ::Message & instance) = 0;

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

  virtual ::CORBA::Boolean _is_a (const char *type_id);
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);

protected:
  // Abstract or local interface only.
  MessageDataReaderView (void);

  

  virtual ~MessageDataReaderView (void);

private:
  // Private and unimplemented for concrete interfaces.
  MessageDataReaderView (const MessageDataReaderView &);

  void operator= (const MessageDataReaderView &);
};

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::MessageSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::MessageSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_MESSAGETYPESUPPORTINTERFACE__TRAITS_)
#define _MESSAGETYPESUPPORTINTERFACE__TRAITS_

  template<>
  struct HELLOWORLD_STUB_Export Objref_Traits< ::MessageTypeSupportInterface>
  {
    static ::MessageTypeSupportInterface_ptr duplicate (
        ::MessageTypeSupportInterface_ptr p);
    static void release (
        ::MessageTypeSupportInterface_ptr p);
    static ::MessageTypeSupportInterface_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MessageTypeSupportInterface_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MESSAGEDATAWRITER__TRAITS_)
#define _MESSAGEDATAWRITER__TRAITS_

  template<>
  struct HELLOWORLD_STUB_Export Objref_Traits< ::MessageDataWriter>
  {
    static ::MessageDataWriter_ptr duplicate (
        ::MessageDataWriter_ptr p);
    static void release (
        ::MessageDataWriter_ptr p);
    static ::MessageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MessageDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MESSAGEDATAREADER__TRAITS_)
#define _MESSAGEDATAREADER__TRAITS_

  template<>
  struct HELLOWORLD_STUB_Export Objref_Traits< ::MessageDataReader>
  {
    static ::MessageDataReader_ptr duplicate (
        ::MessageDataReader_ptr p);
    static void release (
        ::MessageDataReader_ptr p);
    static ::MessageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MessageDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MESSAGEDATAREADERVIEW__TRAITS_)
#define _MESSAGEDATAREADERVIEW__TRAITS_

  template<>
  struct HELLOWORLD_STUB_Export Objref_Traits< ::MessageDataReaderView>
  {
    static ::MessageDataReaderView_ptr duplicate (
        ::MessageDataReaderView_ptr p);
    static void release (
        ::MessageDataReaderView_ptr p);
    static ::MessageDataReaderView_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MessageDataReaderView_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_visitor_sequence\cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_MessageSeq_H_
#define _TAO_CDR_OP_MessageSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


HELLOWORLD_STUB_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const MessageSeq &_tao_sequence);
HELLOWORLD_STUB_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    MessageSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_MessageSeq_H_ */

// TAO_IDL - Generated from
// c:\users\dfeiock.ads\documents\sem\middleware\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "HelloWorldDcpsC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

