
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SubAppDDSAdapter
// ------------------------------
#ifndef SUBAPPDDSADAPTER_EXPORT_H
#define SUBAPPDDSADAPTER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SUBAPPDDSADAPTER_HAS_DLL)
#  define SUBAPPDDSADAPTER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SUBAPPDDSADAPTER_HAS_DLL */

#if !defined (SUBAPPDDSADAPTER_HAS_DLL)
#  define SUBAPPDDSADAPTER_HAS_DLL 1
#endif /* ! SUBAPPDDSADAPTER_HAS_DLL */

#if defined (SUBAPPDDSADAPTER_HAS_DLL) && (SUBAPPDDSADAPTER_HAS_DLL == 1)
#  if defined (SUBAPPDDSADAPTER_BUILD_DLL)
#    define SubAppDDSAdapter_Export ACE_Proper_Export_Flag
#    define SUBAPPDDSADAPTER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SUBAPPDDSADAPTER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SUBAPPDDSADAPTER_BUILD_DLL */
#    define SubAppDDSAdapter_Export ACE_Proper_Import_Flag
#    define SUBAPPDDSADAPTER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SUBAPPDDSADAPTER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SUBAPPDDSADAPTER_BUILD_DLL */
#else /* SUBAPPDDSADAPTER_HAS_DLL == 1 */
#  define SubAppDDSAdapter_Export
#  define SUBAPPDDSADAPTER_SINGLETON_DECLARATION(T)
#  define SUBAPPDDSADAPTER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SUBAPPDDSADAPTER_HAS_DLL == 1 */

// Set SUBAPPDDSADAPTER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SUBAPPDDSADAPTER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SUBAPPDDSADAPTER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SUBAPPDDSADAPTER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SUBAPPDDSADAPTER_NTRACE */

#if (SUBAPPDDSADAPTER_NTRACE == 1)
#  define SUBAPPDDSADAPTER_TRACE(X)
#else /* (SUBAPPDDSADAPTER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SUBAPPDDSADAPTER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SUBAPPDDSADAPTER_NTRACE == 1) */

#endif /* SUBAPPDDSADAPTER_EXPORT_H */

// End of auto generated file.
