// -*- IDL -*-

//=============================================================================
/**
 *  @file         OpenSplice_Events.idl
 *
 *  $Id$
 *
 *  @author       James H. Hill
 */
//=============================================================================

#ifndef _ICCM_OPENSPLICE_EVENTS_IDL_
#define _ICCM_OPENSPLICE_EVENTS_IDL_

#include "cuts/iccm/arch/dds/servant/DDS_Events.idl"

module Components
{
  module OpenSplice
  {
    /**
     * Extension interface for connecting to subscriber using CCM
     * component connections. The event consumer exposes methods that
     * control what topics it listens to.
     */
    interface EventConsumer : ::Components::DDS::EventConsumer
    {

    };
  };
};

#endif  // !defined _ICCM_OPENSPLICE_EVENTS_IDL_
