// -*- C++ -*-

//=============================================================================
/**
 *  @file         RTIDDS_Publisher_Table.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_RTIDDS_PUBLISHER_TABLE_H_
#define _ICCM_RTIDDS_PUBLISHER_TABLE_H_

#include "RTIDDS.h"

#endif  // !defined _ICCM_RTIDDS_PUBLISHER_TABLE_H_
