// -*- C++ -*-

//=============================================================================
/**
 * @file          Command_Subtitution.h
 *
 * $Id$
 *
 * @author        James H. Hill
 */
//=============================================================================

#ifndef _CUTS_COMMAND_SUBSTITUTION_H_
#define _CUTS_COMMAND_SUBSTITUTION_H_

#include "ace/SStringfwd.h"

/**
 * @class CUTS_Command_Substitution
 *
 * Substitutes a command in a string with the output generated by the
 * command. Commands are defined by characters enclosed by `', similar
 * to a shell script on Unix platforms.
 */
class CUTS_Command_Substitution
{
public:
  /// Default constructor.
  CUTS_Command_Substitution (void);

  /// Destructor.
  ~CUTS_Command_Substitution (void);

  /**
   * Evaluate a string. This will substitute all commands in \a str with
   * the output it generates.
   *
   * @param[in]         str           Source string
   * @param[out]        result        String with substituted values
   * @retval            true          Evaluation succeeded
   * @retval            false         Evaluation failed
   */
  bool evaluate (const char * str, ACE_CString & result);
};

#endif  // !defined _CUTS_COMMAND_SUBSTITUTION_H_
