// -*- IDL -*-

#ifndef _MODELDDSDATA_DDS_IDL_
#define _MODELDDSDATA_DDS_IDL_

module CUTS_DDS
{
  module Outer
  {
    module Inner
    {
      struct Data_DDS
      {
        // data member: id
        long id;

        // data member: urgent
        boolean urgent;
      };
    };

    struct TestData_DDS
    {
      // data member: packet
      ::CUTS_DDS::Outer::Inner::Data_DDS packet;

      // data member: key
      short key;
    };
  };
};

#endif  // _MODELDDSDATA_DDS_IDL_

