
#ifndef MODELDDSDATA_IDL
#define MODELDDSDATA_IDL

#include <Components.idl>

module Outer
{
  module Inner
  {
    struct Data_DDS
    {
      boolean urgent;
      long id;
      string name;
    };
  };
  
  eventtype TestData_DDS
  {
    public Outer::Inner::Data_DDS packet;
    public short key;
  };
};

#endif // MODELDDSDATA_IDL

