
#ifndef SIMPLECOMPONENT_IDL
#define SIMPLECOMPONENT_IDL

#include <Components.idl>
#include "ModelDDSData.idl"

module Example
{
  component SimpleComponent
  {
    consumes Outer::TestData_DDS processEvent;
    
    emits Outer::TestData_DDS emitEvent;
    
    publishes Outer::TestData_DDS publishEvent;
  };
  
  home SimpleComponentHome
    manages SimpleComponent
  {
  };
};

#endif // SIMPLECOMPONENT_IDL

