#ifndef MODEL_DDS_DATA_IDL
#define MODEL_DDS_DATA_IDL

module Outer
{
  module Inner
  {
    struct Data_DDS
    {
      string name;
      long id;
      boolean urgent;
    };
  };
  
//#pragma DCPS_DATA_TYPE "Outer::TestData_DDS"
//#pragma DCPS_DATA_KEY "Outer::TestData_DDS key"
  struct TestData_DDS
  {
    unsigned short key;
    Inner::Data_DDS packet;
  };
  #pragma keylist TestData_DDS
};

#endif // MODEL_DDS_DATA_IDL