// -*- IDL -*-

#ifndef _MODELDDSDATA_OPSL_IDL_
#define _MODELDDSDATA_OPSL_IDL_

module CUTS_OSPL
{
  module Outer
  {
    module Inner
    {
      struct Data_DDS
      {
        // data member: name
        string name;

        // data member: id
        long id;

        // data member: urgent
        boolean urgent;
      };
    };

    struct TestData_DDS
    {
      // data member: packet
      ::CUTS_OSPL::Outer::Inner::Data_DDS packet;

      // data member: key
      short key;
    };

    // define the keylist for the struct/event.
    #pragma keylist TestData_DDS
  };
};

#endif  // _MODELDDSDATA_OPSL_IDL_

