// -*- IDL -*-

#ifndef _MODEL_DDS_DATA_IDL_
#define _MODEL_DDS_DATA_IDL_

#if defined (__DDS_IDL__)
#define eventtype struct
#define public
#else
#include <Components.idl>
#endif

module Outer
{
  module Inner
  {
    eventtype Data_DDS
    {
      public string name;
      public long id;
      public boolean urgent;
    };
  };
  
//#pragma DCPS_DATA_TYPE "Outer::TestData_DDS"
//#pragma DCPS_DATA_KEY "Outer::TestData_DDS key"

  eventtype TestData_DDS
  {
    public unsigned short key;
    public Inner::Data_DDS packet;
  };

  #pragma keylist TestData_DDS
};

#endif // _MODEL_DDS_DATA_IDL_
