#ifndef PUBAPPDDSCOMPONENT_IDL
#define PUBAPPDDSCOMPONENT_IDL

#include "DummyEvent.idl"

module Outer
{
  component PubAppDDSComponent
  {
    publishes ::Outer::TestData_DDS app_op_send;
  };
};

#endif // PUBAPPDDSCOMPONENT_IDL