#ifndef PUBAPPDDSCOMPONENT_IDL
#define PUBAPPDDSCOMPONENT_IDL

#include "DummyEvent.idl"

module Outer
{
  component PubAppDDSComponent
  {
    publishes CUTS_DDS::Dummy app_op_send;
  };
};

#endif // PUBAPPDDSCOMPONENT_IDL