
#ifndef SIMPLECOMPONENT_IDL
#define SIMPLECOMPONENT_IDL

#include <Components.idl>
#include "ModelDDSData.idl"

module Example
{
  component SimpleComponent
  {
    consumes Outer::TestData_DDS tcpip_read_test_data;
    
    consumes Outer::TestData_DDS corba_read_test_data;
    
    consumes Outer::TestData_DDS dds_read_test_data;
    
    emits Outer::TestData_DDS app_op_dds;
    
    emits Outer::TestData_DDS app_op_corba;
    
    publishes Outer::TestData_DDS app_op_tcpip;
  };
  
  home SimpleComponentHome
    manages SimpleComponent
  {
  };
};

#endif // SIMPLECOMPONENT_IDL

