// -*- IDL -*-

#ifndef _SUBAPPDDSCOMPONENT_IDL_
#define _SUBAPPDDSCOMPONENT_IDL_

#include "ModelDDSData.idl"

module Outer
{
  component SubAppDDSComponent
  {
    consumes ::Outer::TestData_DDS app_op_recv;
  };
};

#endif // _SUBAPPDDSCOMPONENT_IDL_
