
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl TPUT_RECEIVER_COMPONENT
// ------------------------------
#ifndef TPUT_RECEIVER_COMPONENT_EXPORT_H
#define TPUT_RECEIVER_COMPONENT_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TPUT_RECEIVER_COMPONENT_HAS_DLL)
#  define TPUT_RECEIVER_COMPONENT_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TPUT_RECEIVER_COMPONENT_HAS_DLL */

#if !defined (TPUT_RECEIVER_COMPONENT_HAS_DLL)
#  define TPUT_RECEIVER_COMPONENT_HAS_DLL 1
#endif /* ! TPUT_RECEIVER_COMPONENT_HAS_DLL */

#if defined (TPUT_RECEIVER_COMPONENT_HAS_DLL) && (TPUT_RECEIVER_COMPONENT_HAS_DLL == 1)
#  if defined (TPUT_RECEIVER_COMPONENT_BUILD_DLL)
#    define TPUT_RECEIVER_COMPONENT_Export ACE_Proper_Export_Flag
#    define TPUT_RECEIVER_COMPONENT_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TPUT_RECEIVER_COMPONENT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TPUT_RECEIVER_COMPONENT_BUILD_DLL */
#    define TPUT_RECEIVER_COMPONENT_Export ACE_Proper_Import_Flag
#    define TPUT_RECEIVER_COMPONENT_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TPUT_RECEIVER_COMPONENT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TPUT_RECEIVER_COMPONENT_BUILD_DLL */
#else /* TPUT_RECEIVER_COMPONENT_HAS_DLL == 1 */
#  define TPUT_RECEIVER_COMPONENT_Export
#  define TPUT_RECEIVER_COMPONENT_SINGLETON_DECLARATION(T)
#  define TPUT_RECEIVER_COMPONENT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TPUT_RECEIVER_COMPONENT_HAS_DLL == 1 */

// Set TPUT_RECEIVER_COMPONENT_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TPUT_RECEIVER_COMPONENT_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TPUT_RECEIVER_COMPONENT_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TPUT_RECEIVER_COMPONENT_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TPUT_RECEIVER_COMPONENT_NTRACE */

#if (TPUT_RECEIVER_COMPONENT_NTRACE == 1)
#  define TPUT_RECEIVER_COMPONENT_TRACE(X)
#else /* (TPUT_RECEIVER_COMPONENT_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TPUT_RECEIVER_COMPONENT_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TPUT_RECEIVER_COMPONENT_NTRACE == 1) */

#endif /* TPUT_RECEIVER_COMPONENT_EXPORT_H */

// End of auto generated file.
