#ifndef MODEL_DATA_IDL
#define MODEL_DATA_IDL

#include "Components.idl"

module Outer
{
  module Inner
  {
    struct Data_IDL
    {
      string name;
      long id;
      boolean urgent;
    };
  };
  
  eventtype TestData_IDL
  {
    public unsigned short key;
    public Inner::Data_IDL packet;
  };
};

#endif // MODEL_DATA_IDL