// -*- IDL -*-

//=============================================================================
/**
 * @file          Application.idl
 *
 * $Id$
 *
 * @author        James H. Hill
 */
//=============================================================================

#ifndef _APPLICATION_IDL_
#define _APPLICATION_IDL_

module cuts
{
  module java
  {
    module jbi
    {
      module deployment
      {
        /** 
         * @interface Application
         *
         * Common interface exposed by all application objects.
         */
        interface Application
        {
          void start ();

          void finishLaunch ();
        };
      };
    };
  };
};

#endif  // !defined _APPLICATION_IDL_
