// -*- IDL -*-

#ifndef _JBI_APPLICATION_PROCESS_IDL_
#define _JBI_APPLICATION_PROCESS_IDL_

module cuts
{
  module java
  {
    module jbi 
    {
      module deployment
      {
        interface ApplicationProcess
        {
          readonly attribute string name;

          void installClient (in string instanceName);

          void uninstallClient (in string instanceName);

          void shutdown ();
        };
      };
    };
  };
};

#endif  // !defined _JBI_SINGLE_PROCESS_IDL_
