// -*- IDL -*-

#ifndef _JBI_NODE_APPLICATION_CALLBACK_IDL_
#define _JBI_NODE_APPLICATION_CALLBACK_IDL_

#include "ApplicationProcess.idl"

module cuts
{
  module java
  {
    module jbi
    {
      module deployment
      {
        interface NodeApplicationCallback
        {
          void registerProcess (in ApplicationProcess process);

          void unregisterProcess (in ApplicationProcess process);
        };
      };
    };
  };
};

#endif  // !defined _JBI_NODE_APPLICATION_CALLBACK_IDL_
