// -*- C++ -*-

//=============================================================================
/**
 *  @file         QpidPB_Container.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_QPIDPB_CONTAINER_H_
#define _ICCM_QPIDPB_CONTAINER_H_

#include "cuts/iccm/deployment/Container_T.h"

#include "../servant/QpidPB_Servant.h"
#include "QpidPB_Container_Strategy.h"

namespace iCCM
{

// Forward decl.
class QpidPB_Component_Instance_Handler;

/**
 * @class QpidPB_Container
 *
 * iCCM container implementation for the QpidPB architecture.
 */
class ICCM_QPIDPB_DEPLOYMENT_HANDLERS_Export QpidPB_Container :
  public Container_T <QpidPB_Container,
                      QpidPB_Component_Instance_Handler,
                      QpidPB_Container_Strategy,
                      QpidPB_Servant>
{
public:
  /// Type definition of the base type.
  typedef
    Container_T <QpidPB_Container,
                 QpidPB_Component_Instance_Handler,
                 QpidPB_Container_Strategy,
                 QpidPB_Servant> base_type;

  /**
   * Initializing constructor.
   *
   * @param[in]           handler           Pointer to instance handler
   * @param[in]           poa               PortableServer for container
   */
  QpidPB_Container (
    QpidPB_Component_Instance_Handler * handler,
     ::PortableServer::POA_ptr the_POA);

  /// Destructor.
  virtual ~QpidPB_Container (void);
};

}

#if defined (__CUTS_INLINE__)
#include "QpidPB_Container.inl"
#endif

#endif  // !defined _ICCM_QpidPB_CONTAINER_H_
