
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SCATTER_DEPLOYMENT_PARSER
// ------------------------------
#ifndef SCATTER_DEPLOYMENT_PARSER_EXPORT_H
#define SCATTER_DEPLOYMENT_PARSER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SCATTER_DEPLOYMENT_PARSER_HAS_DLL)
#  define SCATTER_DEPLOYMENT_PARSER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SCATTER_DEPLOYMENT_PARSER_HAS_DLL */

#if !defined (SCATTER_DEPLOYMENT_PARSER_HAS_DLL)
#  define SCATTER_DEPLOYMENT_PARSER_HAS_DLL 1
#endif /* ! SCATTER_DEPLOYMENT_PARSER_HAS_DLL */

#if defined (SCATTER_DEPLOYMENT_PARSER_HAS_DLL) && (SCATTER_DEPLOYMENT_PARSER_HAS_DLL == 1)
#  if defined (SCATTER_DEPLOYMENT_PARSER_BUILD_DLL)
#    define SCATTER_DEPLOYMENT_PARSER_Export ACE_Proper_Export_Flag
#    define SCATTER_DEPLOYMENT_PARSER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SCATTER_DEPLOYMENT_PARSER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SCATTER_DEPLOYMENT_PARSER_BUILD_DLL */
#    define SCATTER_DEPLOYMENT_PARSER_Export ACE_Proper_Import_Flag
#    define SCATTER_DEPLOYMENT_PARSER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SCATTER_DEPLOYMENT_PARSER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SCATTER_DEPLOYMENT_PARSER_BUILD_DLL */
#else /* SCATTER_DEPLOYMENT_PARSER_HAS_DLL == 1 */
#  define SCATTER_DEPLOYMENT_PARSER_Export
#  define SCATTER_DEPLOYMENT_PARSER_SINGLETON_DECLARATION(T)
#  define SCATTER_DEPLOYMENT_PARSER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SCATTER_DEPLOYMENT_PARSER_HAS_DLL == 1 */

// Set SCATTER_DEPLOYMENT_PARSER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SCATTER_DEPLOYMENT_PARSER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SCATTER_DEPLOYMENT_PARSER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SCATTER_DEPLOYMENT_PARSER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SCATTER_DEPLOYMENT_PARSER_NTRACE */

#if (SCATTER_DEPLOYMENT_PARSER_NTRACE == 1)
#  define SCATTER_DEPLOYMENT_PARSER_TRACE(X)
#else /* (SCATTER_DEPLOYMENT_PARSER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SCATTER_DEPLOYMENT_PARSER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SCATTER_DEPLOYMENT_PARSER_NTRACE == 1) */

#endif /* SCATTER_DEPLOYMENT_PARSER_EXPORT_H */

// End of auto generated file.
