// -*- IDL -*-

//=============================================================================
/**
 * @file        logging.idl
 *
 * $Id$
 *
 * @author      James H. Hill
 */
//=============================================================================

#ifndef _CUTS_LOGGING_CLIENT_IDL_
#define _CUTS_LOGGING_CLIENT_IDL_

#include "../logging.idl"

module CUTS
{
  /**
   * @interface Logger
   *
   * Interface for logging messages so they are assoicated with a
   * test run in CUTS.
   */
  interface Logger
  {
    /**
     * Log a message to the logging client.
     *
     * @param[in]       timestamp         Timestamp of the message
     * @param[in]       severity          Severity of the message
     * @param[in]       thread_id          Threadid of the message
     * @param[in]       message           Content of the message
     */
    oneway void log (in ::CUTS::LogMessage logmsg);

    /// Get the UUID associated with the logger.
    readonly attribute ::CUTS::UUID uuid;
  };

  /**
   * @interface LoggingClient
   */
  interface LoggingClient
  {
    /**
     * Locate the test logger factory for the specified test. The logger
     * factory is initially created when a server registers a
     * TestLoggerServer using the TestLoggerClientManager interface.
     *
     * @param[in]       uid           UUID of the test/factory
     * @return          Reference to logger factory
     */
    ::CUTS::Logger get_logger (in ::CUTS::UUID test);

    void release (in ::CUTS::Logger obj);
  };
};

#endif  // !defined _CUTS_LOGGING_CLIENT_IDL_
