#ifndef _HELLOWORLD_IDL_
#define _HELLOWORLD_IDL_


#pragma ciao lem "HelloWorldE.idl"

#pragma ndds typesupport "HelloWorldSupport.h"
#pragma opendds typesupport "HelloWorldTypeSupportC.h"
#pragma splice typesupport "HelloWorldDscpC.h"

/*
interface Messenger
{
  void increment_count ();
  
};
*/

#pragma DCPS_DATA_TYPE "Message"
#pragma DCPS_DATA_KEY "Message time"

struct Message
{
  long time;  // @key
  
  string content;
  
};

#pragma keylist Message time


#endif    // !defined _HELLOWORLD_IDL_

