// -*- IDL -*-

#ifndef _APPLICATION_MANAGER_IDL_
#define _APPLICATION_MANAGER_IDL_

#include "Deployment.idl"
#include "Application.idl"

module CUTS
{
  module jbi
  {
    module deployment
    {
      /// Type definition for a collection of applicatoins.
      typedef sequence <Application> Applications;

      /**
       * @interface ApplicationManager
       */
      interface ApplicationManager
      {
        /// Start the launch sequence for the application manager
        Application startLaunch ();

        /**
         * Destroy the specified application.
         *
         * @param[in]     app         Target application to destroy.
         */
        void destroyApplication (in Application app);
      };
    };
  };
};

#endif  // !defined _APPLICATION_MANAGER_IDL_
