// -*- C++ -*-

//=============================================================================
/**
 *  @file         QpidPB_EventConsumer.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_QPIDPB_EVENTCONSUMER_H_
#define _ICCM_QPIDPB_EVENTCONSUMER_H_

#include "cuts/iccm/servant/EventConsumer.h"

#include "QpidPB_EventsS.h"
#include "QpidPB_svnt_export.h"

#include "qpid/client/Connection.h"

namespace iCCM
{

// Forward decl.
class QpidPB_Servant;

/**
 * @class QpidPB_EventConsumer
 *
 * Servant implmentation of the ::Components::QpidPB::EventConsumer
 * object that is defined in QpidPB_Events.idl. This class also
 * inherits from iCCM::EventConsumer so that it can be used in the Servant_T
 * class, which implements common behavior for all CCM servant objects.
 */
class ICCM_QPIDPB_SVNT_Export QpidPB_EventConsumer :
  public virtual EventConsumer,
  public virtual ::POA_Components::QpidPB::EventConsumer
{
public:
  /// Default constructor.
  QpidPB_EventConsumer (void);

  /// Destructor.
  virtual ~QpidPB_EventConsumer (void);

  /// Configure the consumer
  virtual void configure (const char * host, int port, const char * queue);

protected:
  /// Connection properties
  std::string host_;
  int port_;
  std::string queue_;

  /// The qpid connection
  qpid::client::Connection connection_;
};

}

#if defined (__CUTS_INLINE__)
#include "QpidPB_EventConsumer.inl"
#endif

#endif  // !defined _ICCM_QpidPB_EVENTCONSUMER_H_
