
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl QUOTAS_SPECIFICATION
// ------------------------------
#ifndef QUOTAS_SPECIFICATION_EXPORT_H
#define QUOTAS_SPECIFICATION_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (QUOTAS_SPECIFICATION_HAS_DLL)
#  define QUOTAS_SPECIFICATION_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && QUOTAS_SPECIFICATION_HAS_DLL */

#if !defined (QUOTAS_SPECIFICATION_HAS_DLL)
#  define QUOTAS_SPECIFICATION_HAS_DLL 1
#endif /* ! QUOTAS_SPECIFICATION_HAS_DLL */

#if defined (QUOTAS_SPECIFICATION_HAS_DLL) && (QUOTAS_SPECIFICATION_HAS_DLL == 1)
#  if defined (QUOTAS_SPECIFICATION_BUILD_DLL)
#    define QUOTAS_SPECIFICATION_Export ACE_Proper_Export_Flag
#    define QUOTAS_SPECIFICATION_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define QUOTAS_SPECIFICATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* QUOTAS_SPECIFICATION_BUILD_DLL */
#    define QUOTAS_SPECIFICATION_Export ACE_Proper_Import_Flag
#    define QUOTAS_SPECIFICATION_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define QUOTAS_SPECIFICATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* QUOTAS_SPECIFICATION_BUILD_DLL */
#else /* QUOTAS_SPECIFICATION_HAS_DLL == 1 */
#  define QUOTAS_SPECIFICATION_Export
#  define QUOTAS_SPECIFICATION_SINGLETON_DECLARATION(T)
#  define QUOTAS_SPECIFICATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* QUOTAS_SPECIFICATION_HAS_DLL == 1 */

// Set QUOTAS_SPECIFICATION_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (QUOTAS_SPECIFICATION_NTRACE)
#  if (ACE_NTRACE == 1)
#    define QUOTAS_SPECIFICATION_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define QUOTAS_SPECIFICATION_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !QUOTAS_SPECIFICATION_NTRACE */

#if (QUOTAS_SPECIFICATION_NTRACE == 1)
#  define QUOTAS_SPECIFICATION_TRACE(X)
#else /* (QUOTAS_SPECIFICATION_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define QUOTAS_SPECIFICATION_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (QUOTAS_SPECIFICATION_NTRACE == 1) */

#endif /* QUOTAS_SPECIFICATION_EXPORT_H */

// End of auto generated file.
