// -*- C++ -*-

//=============================================================================
/**
 *  @file         Portico_EventConsumer.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_PORTICO_EVENTCONSUMER_H_
#define _ICCM_PORTICO_EVENTCONSUMER_H_

#include "cuts/iccm/servant/EventConsumer.h"

#include "Portico_EventsS.h"
#include "Portico_svnt_export.h"

#include "ace/Unbounded_Set.h"
#include "Portico_ObjectClass_Factory.h"

namespace iCCM
{

// Forward decl.
class Portico_Servant;

/**
 * @class Portico_EventConsumer
 *
 * Servant implmentation of the ::Components::Portico::EventConsumer
 * object that is defined in Portico_Events.idl. This class also
 * inherits from iCCM::EventConsumer so that it can be used in the Servant_T
 * class, which implements common behavior for all CCM servant objects.
 */
class ICCM_PORTICO_SVNT_Export Portico_EventConsumer :
  public virtual EventConsumer,
  public virtual ::POA_Components::Portico::EventConsumer
{
public:
  /// Default constructor.
  Portico_EventConsumer (void);

  /// Destructor.
  virtual ~Portico_EventConsumer (void);

  /**
   * Initialize this consumer's handle.
   *
   * @param[in]           rtiamb            Pointer to the ambassador
   */
  virtual void init (RTI::RTIambassador * rtiamb) = 0;

  /// Finalize the event consumer.
  virtual void fini (void);

  /**
   * Dispatch an event. This will make an upcall to the
   * contained servant via the contained upcall method.
   *
   * @param[in]           attr              Event attributes
   */
  virtual void dispatch_event (const RTI::AttributeHandleValuePairSet &) = 0;

  /**
   * Observe the specified object.
   *
   * @param[in]           oid               Object instance handle
   */
  virtual void observe_object (const char * tag);

  /**
   * Stop observing the specified object.
   *
   * @param[in]           oid               Object instance handle
   */
  virtual void unobserve_object (const char * tag);

  /// Test of the object handle is observed.
  bool is_observed (RTI::ObjectHandle handle) const;

protected:
  /// Pointer to the ambassador.
  RTI::RTIambassador * rtiamb_;

  /// The publisher's target object handle.
  RTI::ObjectHandle obj_handle_;

  /// Set of object instances this consumer handles.
  ACE_Unbounded_Set < RTI::ObjectHandle > handles_;
};

}

#if defined (__CUTS_INLINE__)
#include "Portico_EventConsumer.inl"
#endif

#endif  // !defined _ICCM_Portico_EVENTCONSUMER_H_
