// -*- IDL -*-

//=============================================================================
/**
 * @file        logging.idl
 *
 * $Id$
 *
 * @author      James H. Hill
 */
//=============================================================================

#ifndef _CUTS_LOGGING_CLIENT_IDL_
#define _CUTS_LOGGING_CLIENT_IDL_

#include "../logging.idl"

module CUTS
{
  /**
   * @interface TestLogger
   *
   * Interface for logging messages so they are assoicated with a
   * test run in CUTS.
   */
  interface TestLogger
  {
    /**
     * Log a message to the logging client.
     *
     * @param[in]       timestamp         Timestamp of the message
     * @param[in]       severity          Severity of the message
     * @param[in]       message           Content of the message
     */
    void log (in CUTS::TimeValue timestamp,
              in long severity,
              in MessageText message);

    void batch_log (in LogMessages msgs);

    void start (in unsigned long seconds);

    void stop ();
  };

  /**
   * @interface TestLoggerClient
   *
   * Interface definition for sending messeages to the logging client on
   * a specific host. The test logger client works in conjunction with
   * the CUTS::TestManager.
   */
  interface TestLoggerFactory
  {
    /**
     * Create a new logger from this factory. The logger returned with
     * be associated with the test UUID used to create this factory.
     *
     * @return        Logger object
     */
    TestLogger create ();

    /**
     * Destroy a logger of this factory.
     *
     * @param[in]     logger        Logger object to destroy.
     */
    void destroy (in TestLogger logger);
  };

  /**
   * @interface LocalTestLoggerClient
   */
  interface LocalTestLoggerClient
  {
    /**
     * Locate the test logger factory for the specified test. The logger
     * factory is initially created when a server registers a
     * TestLoggerServer using the TestLoggerClientManager interface.
     *
     * @param[in]       uid           UUID of the test/factory
     * @return          Reference to logger factory
     */
    TestLoggerFactory find (in UUID uid)
      raises (RegistrationNotFound);
  };
};

#endif  // !defined _CUTS_LOGGING_CLIENT_IDL_
