// -*- IDL -*-

#ifndef _MODELDDSDATA_DDS_IDL_
#define _MODELDDSDATA_DDS_IDL_

#if defined (__NDDS__)
#define CUTS_DDS CUTS_NDDS
#elif defined (__OSPL__)
#define CUTS_DDS CUTS_OSPL
#endif

module CUTS_DDS
{
  module Outer
  {
    module Inner
    {
      struct Data_DDS
      {
        // data member: name
        string name;

        // data member: urgent
        boolean urgent;

        // data member: id
        long id;
      };
    };

    struct TestData_DDS
    {
      // data member: packet
      ::CUTS_DDS::Outer::Inner::Data_DDS packet;

      // data member: key
      short key;
    };

    #if defined (__OSPL__)
    // define the keylist for the struct/event.
    #pragma keylist TestData_DDS
    #endif
  };
};

#endif  // _MODELDDSDATA_DDS_IDL_

