// -*- IDL -*-

#ifndef _TRON_DEPLOYMENT_HANDLER_IDL_
#define _TRON_DEPLOYMENT_HANDLER_IDL_

module Tron
{
  interface TestAdapter
  {
    // Notify the test adapter that initialization is complete and
    // control can return from the adapter_new call.
    void initialization_complete ();

    /// Notify the test adapter that activation is complete. This
    /// will allow Tron to return from adapter_start and begin executing the 
    /// simulation.
    void activate_complete ();
  };

  interface TestAdapterCallback 
  {
    /**
     * Set the test adapter for the callback. This allows the callback
     * to send deployment related signals into the Tron simulation.
     */
    void set_test_adapter (in TestAdapter test_adapter);
  };
};

#endif  // !defined _TRON_DEPLOYMENT_HANDLER_IDL_
