// -*- C++ -*-

//=============================================================================
/**
 *  @file TAO_Component_Instance_Handler.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_TAO_COMPONENT_INSTANCE_HANDLER_H_
#define _ICCM_TAO_COMPONENT_INSTANCE_HANDLER_H_

#include "cuts/iccm/deployment/Component_Instance_Handler_T.h"
#include "TAO_Container.h"

namespace iCCM
{

/**
 * @class TAO_Component_Instance_Handler
 *
 * TAO implementation of the deployment handlers for component
 * instances.
 */
class  ICCM_TAO_DEPLOYMENT_HANDLERS_Export TAO_Component_Instance_Handler :
  public Component_Instance_Handler_T <TAO_Component_Instance_Handler,
                                       ::DAnCE::InstanceDeploymentHandler,
                                       TAO_Container>
{
public:
  /// Type definition of the base type.
  typedef Component_Instance_Handler_T <TAO_Component_Instance_Handler,
                                        ::DAnCE::InstanceDeploymentHandler,
                                        TAO_Container> base_type;

  /// Default constructor.
  TAO_Component_Instance_Handler (void);

  /// Destructor.
  virtual ~TAO_Component_Instance_Handler (void);

  /**
   * Configure the instance handler. The deployment properties passed
   * into this function are the ones attached to the Node in the
   * deployment model.
   *
   * @param[in]           config          Configuration properties
   */
  virtual void configure (const Deployment::Properties & config);

  /// Close the instance handler.
  virtual void close (void);

private:
  /// INSERT YOUR VARIABLES HERE
};

}

extern "C"
ICCM_TAO_DEPLOYMENT_HANDLERS_Export
::DAnCE::InstanceDeploymentHandler_ptr
create_iCCM_TAO_Component_Instance_Handler (void);

#if defined (__CUTS_INLINE__)
#include "TAO_Component_Instance_Handler.inl"
#endif

#endif  // !defined _ICCM_TAO_COMPONENT_INSTANCE_HANDLER_H_
