// -*- C++ -*-

//=============================================================================
/**
 *  @file         TAO_Container.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//=============================================================================

#ifndef _ICCM_TAO_CONTAINER_H_
#define _ICCM_TAO_CONTAINER_H_

#include "cuts/iccm/deployment/Container_T.h"

#include "../servant/TAO_Servant.h"
#include "TAO_Container_Strategy.h"

namespace iCCM
{

// Forward decl.
class TAO_Component_Instance_Handler;

/**
 * @class TAO_Container
 *
 * iCCM container implementation for the TAO architecture.
 */
class ICCM_TAO_DEPLOYMENT_HANDLERS_Export TAO_Container :
  public Container_T <TAO_Container,
                      TAO_Component_Instance_Handler,
                      TAO_Container_Strategy,
                      TAO_Servant>
{
public:
  /// Type definition of the base type.
  typedef
    Container_T <TAO_Container,
                 TAO_Component_Instance_Handler,
                 TAO_Container_Strategy,
                 TAO_Servant> base_type;

  /**
   * Initializing constructor.
   *
   * @param[in]           handler           Pointer to instance handler
   * @param[in]           poa               PortableServer for container
   */
  TAO_Container (
    TAO_Component_Instance_Handler * handler,
     ::PortableServer::POA_ptr the_POA);

  /// Destructor.
  virtual ~TAO_Container (void);
};

}

#if defined (__CUTS_INLINE__)
#include "TAO_Container.inl"
#endif

#endif  // !defined _ICCM_TAO_CONTAINER_H_
