// -*- C++ -*-

//==============================================================================
/**
 *  @file       CHAOS_Servant.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//==============================================================================

#ifndef _ICCM_CHAOS_SERVANT_H_
#define _ICCM_CHAOS_SERVANT_H_

#include "cuts/iccm/servant/Servant.h"

#include "CHAOS_EventConsumer.h"
#include "CHAOS_Publisher.h"
#include "CHAOS_Publisher_Table.h"

namespace iCCM
{

/**
 * @class CHAOS_Servant
 *
 * Base class for all CHAOS servant objects. This class enables
 * the container to send commands to the servant, such as
 * domain-specific configuration information.
 */
class ICCM_CHAOS_SVNT_Export CHAOS_Servant :
  public Servant
{
public:
  /// Trait definitions for iCCM::Servant_T object.
  typedef CHAOS_EventConsumer eventconsumer_type;
  typedef CHAOS_Publisher publisher_type;
  typedef CHAOS_Publisher_Table publisher_table_type;

  /// Default constructor.
  CHAOS_Servant (const char * name);

  /// Destructor.
  virtual ~CHAOS_Servant (void);
};

}

#if defined (__CUTS_INLINE__)
#include "CHAOS_Servant.inl"
#endif

#endif  // !defined _ICCM_CHAOS_SERVANT_H_
