// -*- C++ -*-

//==============================================================================
/**
 *  @file       CHAOS_Servant.h
 *
 *  $Id$
 *
 *  Code generated by iCCM skeleton project generator that is include
 *  in the CUTS (http://cuts.cs.iupui.edu) and developed by:
 *
 *      Software Engineering & Distributed System (SEDS) Group
 *      Indiana Univesity-Purdue University Indianapolis
 *      Indianapolis, IN 46202
 */
//==============================================================================

#ifndef _ICCM_CHAOS_SERVANT_H_
#define _ICCM_CHAOS_SERVANT_H_

#include "cuts/iccm/servant/Servant.h"

#include "CHAOS_EventConsumer.h"
#include "CHAOS_Publisher.h"
#include "CHAOS_Publisher_Table.h"

namespace iCCM
{

/**
 * @class CHAOS_Servant
 *
 * Base class for all CHAOS servant objects. This class enables
 * the container to send commands to the servant, such as
 * domain-specific configuration information.
 */
class ICCM_CHAOS_SVNT_Export CHAOS_Servant :
  public Servant
{
public:
  /// Collection of servants mapped by their architecture type.
  typedef ACE_Hash_Map_Manager <std::string,
                                iCCM::Servant *,
                                ACE_RW_Thread_Mutex>
                                servant_map_type;


  /// Trait definitions for iCCM::Servant_T object.
  typedef CHAOS_EventConsumer eventconsumer_type;
  typedef CHAOS_Publisher publisher_type;
  typedef CHAOS_Publisher_Table publisher_table_type;

  /// Default constructor.
  CHAOS_Servant (const char * name);

  /// Destructor.
  virtual ~CHAOS_Servant (void);

  const servant_map_type & servants (void) const;

protected:
  ::PortableServer::POA_ptr 
    create_servant_POA (const std::string & name, 
                        ::PortableServer::POA_ptr poa);

  servant_map_type servants_;

  private:
  typedef ACE_Hash_Map_Manager <std::string, 
                        ::PortableServer::POA_var,
                        ACE_RW_Thread_Mutex> servant_poa_map_type;
  servant_poa_map_type servant_POAs_;
};

}

#if defined (__CUTS_INLINE__)
#include "CHAOS_Servant.inl"
#endif

#endif  // !defined _ICCM_CHAOS_SERVANT_H_
